### ISSUE TITLE
Buttons maken

### ISSUE THREAD

**Issue by vasilisvg** [cmda-minor-web/css-to-the-rescue-2223#10]
- [x] Buttons maken voor in welke groep ze komen
- [x] Eventueel ook met hun naam
- [x] Vasilis laten weten hoeveel hoeden hij mee moet nemen

**Comment by shooft** [comment]
Buttons met namen zijn gemaakt - worden maandag uitgedeeld

Buttons voor kennismakingsteams (1 per student) zijn gemaakt (elke button heeft een squad en een onderwerp) - voor de kick-off op woensdag

Vasilis moet 1 hoed meenemen
