### ISSUE TITLE
Tailwind opdracht?

### ISSUE THREAD

**Issue by vasilisvg** [cmda-minor-web/css-to-the-rescue-2223#2]
Gaat dat lukken?
Dus, een hele grote ingewikkelde Tailwind pagina om laten bouwen naar een helemaal moderne CSS pagina, met layers enzo.

**Comment by vasilisvg** [comment]
@shooft is het misschien een idee om deze opdracht te geven aan iemand die een Tailwind site heeft gemaakt? Dat we ze dan de opdracht geven om die eigen site aan te pakken?

**Comment by vasilisvg** [comment]
Okay, er is een [voorbeeldenpagina](https://tailwindcss.com/showcase) van Tailwind.

**Comment by shooft** [comment]
> @shooft is het misschien een idee om deze opdracht te geven aan iemand die een Tailwind site heeft gemaakt? Dat we ze dan de opdracht geven om die eigen site aan te pakken?

ook een prima plan

zou natuurlijk elk ander framework kunnen zijn (bijv bootstrap) - zolang het maar een beetje grote pagina is (met componenten)

**Comment by joostf** [comment]
Yes! Of een verstokte BEMmer met layers gebruik laten maken van de kracht van specificty in CSS 🚀

**Comment by vasilisvg** [comment]
Ik heb een Tailwind-opdracht toegevoegd. Eis is dat die zelf gemaakt is.
